### ISSUE TITLE
Deploy #10 to stage

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/duke-extend-theme#11]
@pomegranited, I discovered a few typos upon review in stage. 

We'll also need to back out the change you made to the Course Info .main-cta .register button which sends it to https://accounts.oit.duke.edu/onelink/iz78. Please change it back to previous behavior, which I believe was send the user to the onelink login page w/ custom redirect back to the specific course.

We're reviewing the marketing site decision you documented in #7 , do we need to have you restart the stage server to apply it after adding the config in django?

**Comment by pomegranited** [comment]
@profmikegreene I've done the following on stage.extend.duke.edu:
* updated the theme to include your latest https://github.com/DukeLearningInnovation/duke-extend-theme/pull/10
* deleted the redirect from `/register` to `https://accounts.oit.duke.edu/onelink/iz78`

For the [marketing site links](https://github.com/DukeLearningInnovation/duke-extend-theme/pull/7#issuecomment-355174534), you don't need to restart the service, but you do need to wait at least 3 minutes for changes to Site Configuration to take effect.  They are cached for performance reasons.

**Comment by pomegranited** [comment]
@profmikegreene  Using the github issues feature is a great way to communicate about issues on your instance..  I like it!

@bradenmacdonald  maybe we could add an open-craft/help, so we have a way to ping the help list instead of just individuals?

**Comment by bradenmacdonald** [comment]
@pomegranited You can ping @DukeLearningInnovation/opencraft ... but on organizations outside our own you can't ping any `open-craft` groups unfortunately.
